import pandas as pd
import plotly.express as px

# Load data
df = pd.read_csv("../data/supply_chain_data.csv")

# Revenue Generated by the products
fig = px.scatter(df, x="Price", y="Revenue generated", color="Product type", hover_data=["Number of products sold"], trendline="ols")
fig.show()
