import pandas as pd
import plotly.express as px

# Load data
df = pd.read_csv("../data/supply_chain_data.csv")

# Revenue generated by each SKU
revenue_chart = px.line(df, x="SKU", y="Revenue generated", title="Revenue generated by each SKU")
revenue_chart.show()
